export const LOGIN = 'LOGIN';
export const SAVE_DATA_USER = 'SAVE_DATA_USER';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const VERIFY_CODE_FORGOT_PASSWORD = 'VERIFY_CODE_FORGOT_PASSWORD';
export const RESET_NEW_PASSWORD = 'RESET_NEW_PASSWORD';
export const SET_DATA_SIGNUP = 'SET_DATA_SIGNUP';
export const RESET_DATA_SIGNUP = 'RESET_DATA_SIGNUP';
export const UPDATE_PHONE_NUMBER = 'UPDATE_PHONE_NUMBER';
export const VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER';
export const VERIFY_CODE_PHONE_NUMBER = 'VERIFY_CODE_PHONE_NUMBER';

//PROFILE
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_PROFILE_USER = 'GET_PROFILE_USER';
