// UNAUTHENTICATION
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const WELCOME = 'WELCOME';
export const SIGNIN = 'SIGNIN';
export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const ROOM_UNIT_HOMEOWNER = 'ROOM_UNIT_HOMEOWNER';
export const RESETPASSWORD = 'RESETPASSWORD';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const USER_INFORMATION_NAME = 'USER_INFORMATION_NAME';
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const VERIFY_CODE = 'VERIFY_CODE';
export const ROOM_UNIT_PICTURE = 'ROOM_UNIT_PICTURE';
export const USER_INFORMATION_GENDER = 'USER_INFORMATION_GENDER';
export const USER_INFORMATION_COUNTRY = 'USER_INFORMATION_COUNTRY';
export const LIFE_STYLE = 'LIFE_STYLE';
export const LIFE_STYLE_STEP = 'LIFE_STYLE_STEP';
export const HOME = 'HOME';

