// UNAUTHENTICATION
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const WELCOME = 'WELCOME';
export const SIGNIN = 'SIGNIN';
export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const UPDATE_NEW_PASSWORD = 'UPDATE_NEW_PASSWORD';

// ROOM UNIT
// export const ROOM_UNIT_HOMEOWNER = 'ROOM_UNIT_HOMEOWNER';
export const ROOM_UNIT_ADDRESS = 'ROOM_UNIT_ADDRESS';
export const ROOM_UNIT_FURNISHING = 'ROOM_UNIT_FURNISHING';
export const ROOM_UNIT_GALLERY = 'ROOM_UNIT_GALLERY';
export const ROOM_UNIT_KIND_PLACE = 'ROOM_UNIT_KIND_PLACE';
export const ROOM_UNIT_LEASE_PERIOD = 'ROOM_UNIT_LEASE_PERIOD';
export const ROOM_UNIT_PLACE_OFFER = 'ROOM_UNIT_PLACE_OFFER';
export const ROOM_UNIT_PRICE = 'ROOM_UNIT_PRICE';
export const ROOM_UNIT_TYPE_ROOM = 'ROOM_UNIT_TYPE_ROOM';

export const RESETPASSWORD = 'RESETPASSWORD';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const USER_INFORMATION_NAME = 'USER_INFORMATION_NAME';
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const VERIFY_CODE = 'VERIFY_CODE';
export const USER_INFORMATION_GENDER = 'USER_INFORMATION_GENDER';
export const USER_INFORMATION_COUNTRY = 'USER_INFORMATION_COUNTRY';
export const LIFE_STYLE = 'LIFE_STYLE';
export const LIFE_STYLE_STEP = 'LIFE_STYLE_STEP';

// AUTHENTICATE
export const HOME = 'HOME';
export const PROFILE = 'PROFILE';
export const BASIC_INFORMATION = 'HOME_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const HOME_OWNER_LIFE_STYLE = 'HOME_OWNER_LIFE_STYLE';





